### PR TITLE
fix(cli): rework font downloading

### LINKED ISSUE #712: Investigate Changing WOFF Files When Rebuilding Repository
### Description

These commits (https://github.com/fontsource/font-files/commit/de67fff8b972e3dedac930b9c34ac3f88ca59189 and https://github.com/fontsource/font-files/commit/63f05866b9b453c92938f08eece978d28aa184f3) show that when we forcefully rebuild the entire repository which includes redownloading these fonts, the binary WOFF files seem to change.

This does not seem to have an impact on end users as the font files seem valid but is non-deterministic nonetheless.

I've looked into this before, but I've not really been able to pin the issue yet.

### PR DESCRIPTION
**Pull request by Sh4rK**
Fixes the bug that caused the non-variable Google fonts to be downloaded twice, to the same target file, causing indeterministic file changes and slightly broken font files. See #712 for more context.

Fixes #712.

I ran my WOFF size checking script on the output of this PR, and all the previous errors are gone (except manual fonts), so it seems to work.

There are some unexpected changes relative to [font-files@6332265](https://github.com/fontsource/font-files/tree/63322659a79e97016e971081a27d6640eb30382a):

Some fonts are completely missing, but they also don't show up on the Google Fonts website for me:
- fonts/google/arima-madurai
- fonts/google/fredoka-one
- fonts/google/gentium-book-basic
- fonts/google/kantumruy
- fonts/google/merienda-one

A subset is missing from one font, but again, it doesn't show up in the raw metadata for me either:
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-standard-italic.woff2
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-standard-normal.woff2
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-wdth-italic.woff2
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-wdth-normal.woff2
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-wght-italic.woff2
- fonts/variable/radio-canada/files/radio-canada-canadian-aboriginal-wght-normal.woff2

### CODE REVIEW

**Comment by Sh4rK** [comment]
Okay, I completely forgot about the tests, give me some more time :D

**Comment by ayuhito** [comment]
Thanks for making this PR! 🎉 I'll wait to review after the tests are written so I have a better idea of what the expected outputs are. 👍 

> There are some unexpected changes relative to [font-files@6332265](https://github.com/fontsource/font-files/tree/63322659a79e97016e971081a27d6640eb30382a):

Google changes things a lot which includes removing things so this should be a non-issue. See related: #578

**Comment by Sh4rK** [comment]
Should I also add a changeset? If yes, is this a patch level change?

File: packages/cli/src/google/download.ts [hunk 1]
```diff
@@ -19,180 +18,169 @@ const writeDownload = async (url: string, dest: fs.PathLike) => {
...
-
-		const url = pair[1];
-		return { url, dest };
-	});
-
-	const links = [...linksV1, ...linksV2];
-	return links;
+	}
+	// Makes sure that all variants are handled above.
+	return variant;
```
Comment (ayuhito) [inline packages/cli/src/google/download.ts]: This should never happen, right? Maybe a throw is better here?

**Review by ayuhito — COMMENTED** [review]
Huge improvement from before! Thank you! A small suggestion, but otherwise the code looks great. 🎉 

I also went ahead and made the changeset, so you don't need to worry about that.

File: packages/cli/src/google/download.ts (hunk 1 above)
Comment (Sh4rK) [reply packages/cli/src/google/download.ts]: Yes, this should never happen, and this return **compile-time ensures** that. Try to remove one of the if's, and you will get a type error! This ensures that if for whatever reason a new type is added to the union, it will be handled here (... except if it's a string 😬). It works because 'variant' gets narrowed to the 'never' type, which can be assigned to anything (as it will never run). If a new kind were to be added (that's not compatible with string), it will be a type error.

I agree that this is not very intuitive though, so if you do not like it, I will change it to a throw :)

(or we could use something like this https://github.com/aikoven/assert-never)

Comment (ayuhito) [reply packages/cli/src/google/download.ts]: Ooh, I see. Learnt a new pattern here.

I'm a little conflicted since whilst I like the type-safety, I think it hurts immediate readability. A throw conveys the "never should run" nature better imo, but I'm not against you wrapping it in a helper like `assert-never` to get the best of both worlds (although I don't think you should install it as a dep and write your own).

Comment (Sh4rK) [reply packages/cli/src/google/download.ts]: Added an `assertNever` utility function, how is it now?

Comment (ayuhito) [reply packages/cli/src/google/download.ts]: https://github.com/aikoven/assert-never/blob/774509a47569ce42e99d3ae580ca11736e73a297/index.ts#L31 - as a sanity check, we should throw in the assertion. 👍 Should be perfect then.

**Review by ayuhito — APPROVED** [review]
Everything looks good! Once again, thank you for making this PR! 🎉

File: packages/cli/src/google/download.ts (hunk 1 above)
Comment (Sh4rK) [reply packages/cli/src/google/download.ts]: Done!

(I would say that throw can't ever execute, but... unfortunately TypeScript's type system is not entirely immune to such things (`any`), so it's a valid concern.)
